associations.subnetId/terraform import module.route_table_association_10.aws_route_table_association.route_table_association rtb-05cc63256aba18e9b
associations.subnetId/terraform import module.route_table_association_11.aws_route_table_association.route_table_association rtb-0b7b8113a22090948
associations.subnetId/terraform import module.route_table_association_12.aws_route_table_association.route_table_association rtb-0601a2d557c2adf8c
